#!/bin/bash
python convert_remove_null.py ./Hackathon/Test\ Case\ 3_1/S2_Roh_3_1_2.csv
python convert_remove_null.py ./Hackathon/Test\ Case\ 3_1/S2_Roh_3_1_1.csv
python convert_remove_null.py ./Hackathon/Test\ Case\ 3_1/S1_Roh_3_1_1.csv
python convert_remove_null.py ./Hackathon/Test\ Case\ 3_1/S1_Roh_3_1.csv
python convert_remove_null.py ./Hackathon/Test\ Case\ 3_1/S2_Roh_3_1_3.csv
python convert_remove_null.py ./Hackathon/Test\ Case\ 3_1/S1_Roh_3_1_3.csv
python convert_remove_null.py ./Hackathon/Test\ Case\ 3_1/S1_Roh_3_1_2.csv
python convert_remove_null.py ./Hackathon/Test\ Case\ 3_1/S2_Roh_3_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 3/S1_Roh_3.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 3/S2_FFT_Spektrum_3.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 3/S2_Roh_3.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 3/S2_H-FFT_Spektrum_3.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 3/S1_FFT_Spektrum_3.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 3/S1_H-FFT_Spektrum_3.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 2/S2_H-FFT_Spektrum_2_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 2/S1_FFT_Spektrum_2.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 2/S1_Roh_2.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 2/S2_Roh_2.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 2/S1_H-FFT_Spektrum_2_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 2/S2_FFT_Spektrum_2.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 2/S1_Roh_2_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 2/S2_FFT_Spektrum_2_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 2/S2_Roh_2_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 2/S1_H-FFT_Spektrum_2.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 2/S2_H-FFT_Spektrum_2.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 2/S1_FFT_Spektrum_2_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 5/S1_FFT_Spektrum_5.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 5/S2_Roh_5.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 5/S1_H-FFT_Spektrum_5.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 5/S1_Roh_5.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 5/S2_FFT_Spektrum_5.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 5/S2_H-FFT_Spektrum_5.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 1/S1_H-FFT_Spektrum_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 1/S2_Roh_1_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 1/S1_H-FFT_Spektrum_1_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 1/S2_Roh_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 1/S2_FFT_Spektrum_1_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 1/S2_FFT_Spektrum_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 1/S1_Roh_1_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 1/S2_H-FFT_Spektrum_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 1/S2_H-FFT_Spektrum_1_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 1/S1_Roh_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 1/S1_FFT_Spektrum_1_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 1/S1_FFT_Spektrum_1.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 4/S2_Roh_4.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 4/S2_FFT_Spektrum_4.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 4/S1_H-FFT_Spektrum_4.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 4/S1_Roh_4.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 4/S2_H-FFT_Spektrum_4.csv
python convert_remove_null.py ./Hackathon/Messdaten_Hackaton/Test\ Case\ 4/S1_FFT_Spektrum_4.csv
